---
title: "Dynamic Dataset Summary - Statistical & Visual"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Below mentioned are the  Data Exploration Package functions.

## These Functions are Generic, where any tabular data can be passed for the analysis which gives overview of an entire data. 


```{r Libraries, warning=FALSE}
library(psych)
library(Hmisc)
library(corrplot)


```

```{r Data}
#data = iris
data = mtcars

```

```{r Numerical statistics, echo=TRUE, paged.print=TRUE}



####### Numerical statistics############



dataNumericStats <- function(df) {
  numeric_df = as.data.frame(df[ ,sapply(df, is.numeric)])
  statDF = (as.data.frame(psych::describe(numeric_df)))
  statDF <- cbind(rownames(statDF), data.frame(statDF, row.names=NULL))
  
  names(statDF) = c("Variables", "Variance","no.of.datapoints","Mean","Standard Deviation","Median","Trimmed mean","Mean Absloute deviation","Minimum value","Maximun Value", "Range","Skewness","kurtosis","Standard error"  )
  return(statDF)
  }

dataNumericStats(data)


```

## Missing data Percentage



```{r Missing data, echo=TRUE, paged.print=TRUE}
################## Missing data ###########
missingDataNumber <- function(df) {
  missData <- as.data.frame(colMeans(is.na(df))*100)
  missData <- cbind(rownames(missData), data.frame(missData, row.names=NULL))
  names(missData) <- c('Variables',"Missing Percentage")
  return(missData)
}

missingDataNumber(data)



```
## outliers data points


```{r Identifiying outliers, echo=TRUE, warning=FALSE, paged.print=TRUE}


######### Identifiying outliers ###############

dataOutlaiers <- function(df) {
  
  FindOutliers <- function(data) {
    lowerq = quantile(data)[2]
    upperq = quantile(data)[4]
    iqr = upperq - lowerq #Or use IQR(data)
    # we identify extreme outliers
    extreme.threshold.upper = (iqr * 3) + upperq
    extreme.threshold.lower = lowerq - (iqr * 3)
    result <- which(data > extreme.threshold.upper | data < extreme.threshold.lower)
    length(result)
  }
  
  numeric_df = as.data.frame(df[ ,sapply(df, is.numeric)])
  
  outlaiersData <- as.data.frame(apply(numeric_df, 2, FindOutliers))
  outlaiersData <- cbind(rownames(outlaiersData), data.frame(outlaiersData, row.names=NULL))
  names(outlaiersData) <- c('Variables',"Outlaiers count")
  
  return(outlaiersData)
}

dataOutlaiers(data)



```
## Histogram Plot on data

```{r Histogram Plot, echo=TRUE}



########### Histogram Plot ##########


getHistogram <- function(df) {
  numeric_df = as.data.frame(df[ ,sapply(df, is.numeric)])
  #plt <- hist.data.frame(numeric_df)
  return(hist.data.frame(numeric_df))
}

getHistogram(data)



```



## Correlation Plot on data

```{r correlation Plot, echo=TRUE}



########### correlation Plot ##########


getCorrelation <- function(df) {
  numeric_df = as.data.frame(df[ ,sapply(df, is.numeric)])
  cor_data <- cor(numeric_df)
  return(corrplot(cor_data, method="number"))
}

getCorrelation(data)
```
